TYPO3:
  Flow:
    # disable reflection for non psr-0 compliant 3rd party packages
    object:
      excludeClasses:
      'raven.raven': ['.*']

# Sample Configuration for your Production Environment:
#TYPO3:
#  Flow:
#    error:
#      exceptionHandler:
#        className: Albit\Raven\Error\SentryExceptionHandler
#        # Sentry DSN (e.g. "http://public:secret@example.com/1")
#        sentryDsn: ''

